version: "3"

services:
  db:
    image: postgres:14.8
    container_name: api_postgres
    command:
      [
        "postgres",
        "-c",
        "logging_collector=on",
        "-c",
        "log_filename=postgresql.log",
      ]
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - api_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.8
    container_name: api_redis
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - api_redis_data:/data
    restart: always
    environment:
      REDIS_REPLICATION_MODE: master

volumes:
  api_pg_data:
  api_redis_data:
